name: Docker Image CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: ${{ DOCKER_USERNAME}}/phpldapadmin
  DOCKER_IMAGE_TAG: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
  DOCKER_IMAGE_FULLNAME: ${{ DOCKER_IMAGE_NAME }}/${{ DOCKER_IMAGE_TAG }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file image/Dockerfile --tag $DOCKER_IMAGE_FULLNAME
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: $DOCKER_USERNAME
        password: $DOCKER_PASSWORD
    - name: Push to remote
      run: docker push $DOCKER_IMAGE_FULLNAME
